Skip Ruby 3.2+ and AR 6.1 tests on Good Job
We're getting an error due to Ruby 3.2+ and kwargs apparently, some
Rails 6.1 incompatibility with latest Ruby versions.

    ArgumentError: wrong number of arguments (given 1, expected 0)
        test/metrics_collector_test.rb:57:in `block (3 levels) in <module:Judoscale>'

Rails has fixed most of those on 6-1-stable branch, but no stable release
is planned any time soon (that branch is receiving security fixes only),
so let's just skip instead of running everything against the branch for
simplicity, since we're running our tests on other versions and it's a
known Rails 6-1 issue.