Fix Active Record `default_timezone` detection for different versions
Rails 7 moved the `default_timezone` config from `Base` to the main
`ActiveRecord` module, issuing a warning if you try to access it through
`Base`:

- Rails 7

    > ActiveRecord::Base.default_timezone
    DEPRECATION WARNING: ActiveRecord::Base.default_timezone is
    deprecated and will be removed in Rails 7.1.
    Use `ActiveRecord.default_timezone` instead.

    > ActiveRecord.default_timezone
    => :utc

- Rails 6

    > ActiveRecord::Base.default_timezone
    => :utc

    > ActiveRecord.default_timezone
    NoMethodError (undefined method `default_timezone' for ActiveRecord:Module)

To keep compatibility with different versions of Rails / Active Record,
and avoid the deprecation warning on Rails 7, we need to rely on feature
detection there.